// This file is auto-generated by hack/build-components-list.ts
// Do not edit this file directly

type KnownComponents = {
	components: Record<string, { path: string }>;
	icons: Record<string, { path: string }>;
};

export const Components: KnownComponents = {
	components: {
		Accordion: {
			path: "lib/components/Accordion/Accordion.svelte",
		},
		AccordionItem: {
			path: "lib/components/Accordion/AccordionItem.svelte",
		},
		Alert: {
			path: "lib/components/Alert/Alert.svelte",
		},
		BodyLong: {
			path: "lib/components/typography/BodyLong/BodyLong.svelte",
		},
		BodyShort: {
			path: "lib/components/typography/BodyShort/BodyShort.svelte",
		},
		Button: {
			path: "lib/components/Button/Button.svelte",
		},
		Checkbox: {
			path: "lib/components/Checkbox/Checkbox.svelte",
		},
		CheckboxGroup: {
			path: "lib/components/Checkbox/CheckboxGroup.svelte",
		},
		Chips: {
			path: "lib/components/Chips/Chips.svelte",
		},
		ConfirmationPanel: {
			path: "lib/components/ConfirmationPanel/ConfirmationPanel.svelte",
		},
		CopyButton: {
			path: "lib/components/CopyButton/CopyButton.svelte",
		},
		Detail: {
			path: "lib/components/typography/Detail/Detail.svelte",
		},
		ErrorMessage: {
			path: "lib/components/typography/ErrorMessage/ErrorMessage.svelte",
		},
		ErrorSummary: {
			path: "lib/components/ErrorSummary/ErrorSummary.svelte",
		},
		ErrorSummaryItem: {
			path: "lib/components/ErrorSummary/ErrorSummaryItem.svelte",
		},
		Fieldset: {
			path: "lib/components/Fieldset/Fieldset.svelte",
		},
		GuidePanel: {
			path: "lib/components/GuidePanel/GuidePanel.svelte",
		},
		Heading: {
			path: "lib/components/typography/Heading/Heading.svelte",
		},
		Label: {
			path: "lib/components/typography/Label/Label.svelte",
		},
		Link: {
			path: "lib/components/typography/Link/Link.svelte",
		},
		LinkPanel: {
			path: "lib/components/LinkPanel/LinkPanel.svelte",
		},
		LinkPanelDescription: {
			path: "lib/components/LinkPanel/LinkPanelDescription.svelte",
		},
		LinkPanelTitle: {
			path: "lib/components/LinkPanel/LinkPanelTitle.svelte",
		},
		Loader: {
			path: "lib/components/Loader/Loader.svelte",
		},
		Modal: {
			path: "lib/components/Modal/Modal.svelte",
		},
		Pagination: {
			path: "lib/components/Pagination/Pagination.svelte",
		},
		Panel: {
			path: "lib/components/Panel/Panel.svelte",
		},
		Search: {
			path: "lib/components/Search/Search.svelte",
		},
		SearchButton: {
			path: "lib/components/Search/SearchButton.svelte",
		},
		Select: {
			path: "lib/components/Select/Select.svelte",
		},
		Skeleton: {
			path: "lib/components/Skeleton/Skeleton.svelte",
		},
		Step: {
			path: "lib/components/Stepper/Step.svelte",
		},
		Stepper: {
			path: "lib/components/Stepper/Stepper.svelte",
		},
		Switch: {
			path: "lib/components/Switch/Switch.svelte",
		},
		Tab: {
			path: "lib/components/Tabs/Tab.svelte",
		},
		TabList: {
			path: "lib/components/Tabs/TabList.svelte",
		},
		TabPanel: {
			path: "lib/components/Tabs/TabPanel.svelte",
		},
		Table: {
			path: "lib/components/Table/Table.svelte",
		},
		Tabs: {
			path: "lib/components/Tabs/Tabs.svelte",
		},
		Tag: {
			path: "lib/components/Tag/Tag.svelte",
		},
		TextField: {
			path: "lib/components/TextField/TextField.svelte",
		},
		ToggleGroup: {
			path: "lib/components/ToggleGroup/ToggleGroup.svelte",
		},
		ToggleGroupItem: {
			path: "lib/components/ToggleGroup/ToggleGroupItem.svelte",
		},
		Tooltip: {
			path: "lib/components/Tooltip/Tooltip.svelte",
		},
	},
	icons: {
		AirplaneFillIcon: {
			path: "lib/icons/AirplaneFillIcon.svelte",
		},
		AirplaneIcon: {
			path: "lib/icons/AirplaneIcon.svelte",
		},
		AlignBottomFillIcon: {
			path: "lib/icons/AlignBottomFillIcon.svelte",
		},
		AlignBottomIcon: {
			path: "lib/icons/AlignBottomIcon.svelte",
		},
		AlignCenterFillIcon: {
			path: "lib/icons/AlignCenterFillIcon.svelte",
		},
		AlignCenterIcon: {
			path: "lib/icons/AlignCenterIcon.svelte",
		},
		AlignLeftFillIcon: {
			path: "lib/icons/AlignLeftFillIcon.svelte",
		},
		AlignLeftIcon: {
			path: "lib/icons/AlignLeftIcon.svelte",
		},
		AlignMiddleFillIcon: {
			path: "lib/icons/AlignMiddleFillIcon.svelte",
		},
		AlignMiddleIcon: {
			path: "lib/icons/AlignMiddleIcon.svelte",
		},
		AlignRightFillIcon: {
			path: "lib/icons/AlignRightFillIcon.svelte",
		},
		AlignRightIcon: {
			path: "lib/icons/AlignRightIcon.svelte",
		},
		AlignTopFillIcon: {
			path: "lib/icons/AlignTopFillIcon.svelte",
		},
		AlignTopIcon: {
			path: "lib/icons/AlignTopIcon.svelte",
		},
		AllergensFillIcon: {
			path: "lib/icons/AllergensFillIcon.svelte",
		},
		AllergensIcon: {
			path: "lib/icons/AllergensIcon.svelte",
		},
		AngleIcon: {
			path: "lib/icons/AngleIcon.svelte",
		},
		AngleRulerCircleFillIcon: {
			path: "lib/icons/AngleRulerCircleFillIcon.svelte",
		},
		AngleRulerCircleIcon: {
			path: "lib/icons/AngleRulerCircleIcon.svelte",
		},
		AngleRulerTriangleFillIcon: {
			path: "lib/icons/AngleRulerTriangleFillIcon.svelte",
		},
		AngleRulerTriangleIcon: {
			path: "lib/icons/AngleRulerTriangleIcon.svelte",
		},
		AreaChartFillIcon: {
			path: "lib/icons/AreaChartFillIcon.svelte",
		},
		AreaChartIcon: {
			path: "lib/icons/AreaChartIcon.svelte",
		},
		ArrowCirclepathIcon: {
			path: "lib/icons/ArrowCirclepathIcon.svelte",
		},
		ArrowDownIcon: {
			path: "lib/icons/ArrowDownIcon.svelte",
		},
		ArrowForwardFillIcon: {
			path: "lib/icons/ArrowForwardFillIcon.svelte",
		},
		ArrowForwardIcon: {
			path: "lib/icons/ArrowForwardIcon.svelte",
		},
		ArrowLeftIcon: {
			path: "lib/icons/ArrowLeftIcon.svelte",
		},
		ArrowRedoIcon: {
			path: "lib/icons/ArrowRedoIcon.svelte",
		},
		ArrowRightIcon: {
			path: "lib/icons/ArrowRightIcon.svelte",
		},
		ArrowRightLeftIcon: {
			path: "lib/icons/ArrowRightLeftIcon.svelte",
		},
		ArrowUndoIcon: {
			path: "lib/icons/ArrowUndoIcon.svelte",
		},
		ArrowUpIcon: {
			path: "lib/icons/ArrowUpIcon.svelte",
		},
		ArrowsCirclepathIcon: {
			path: "lib/icons/ArrowsCirclepathIcon.svelte",
		},
		ArrowsSquarepathIcon: {
			path: "lib/icons/ArrowsSquarepathIcon.svelte",
		},
		ArrowsUpDownIcon: {
			path: "lib/icons/ArrowsUpDownIcon.svelte",
		},
		BabyWrappedFillIcon: {
			path: "lib/icons/BabyWrappedFillIcon.svelte",
		},
		BabyWrappedIcon: {
			path: "lib/icons/BabyWrappedIcon.svelte",
		},
		BackpackFillIcon: {
			path: "lib/icons/BackpackFillIcon.svelte",
		},
		BackpackIcon: {
			path: "lib/icons/BackpackIcon.svelte",
		},
		BackwardFillIcon: {
			path: "lib/icons/BackwardFillIcon.svelte",
		},
		BackwardIcon: {
			path: "lib/icons/BackwardIcon.svelte",
		},
		BacteriaFillIcon: {
			path: "lib/icons/BacteriaFillIcon.svelte",
		},
		BacteriaIcon: {
			path: "lib/icons/BacteriaIcon.svelte",
		},
		BagdeFillIcon: {
			path: "lib/icons/BagdeFillIcon.svelte",
		},
		BagdeIcon: {
			path: "lib/icons/BagdeIcon.svelte",
		},
		BaggageFillIcon: {
			path: "lib/icons/BaggageFillIcon.svelte",
		},
		BaggageIcon: {
			path: "lib/icons/BaggageIcon.svelte",
		},
		BandageFillIcon: {
			path: "lib/icons/BandageFillIcon.svelte",
		},
		BandageIcon: {
			path: "lib/icons/BandageIcon.svelte",
		},
		BankNoteFillIcon: {
			path: "lib/icons/BankNoteFillIcon.svelte",
		},
		BankNoteIcon: {
			path: "lib/icons/BankNoteIcon.svelte",
		},
		BarChartFillIcon: {
			path: "lib/icons/BarChartFillIcon.svelte",
		},
		BarChartIcon: {
			path: "lib/icons/BarChartIcon.svelte",
		},
		BeaconSignalsFillIcon: {
			path: "lib/icons/BeaconSignalsFillIcon.svelte",
		},
		BeaconSignalsIcon: {
			path: "lib/icons/BeaconSignalsIcon.svelte",
		},
		BedFillIcon: {
			path: "lib/icons/BedFillIcon.svelte",
		},
		BedIcon: {
			path: "lib/icons/BedIcon.svelte",
		},
		BellDotFillIcon: {
			path: "lib/icons/BellDotFillIcon.svelte",
		},
		BellDotIcon: {
			path: "lib/icons/BellDotIcon.svelte",
		},
		BellFillIcon: {
			path: "lib/icons/BellFillIcon.svelte",
		},
		BellIcon: {
			path: "lib/icons/BellIcon.svelte",
		},
		BicycleIcon: {
			path: "lib/icons/BicycleIcon.svelte",
		},
		BoatFillIcon: {
			path: "lib/icons/BoatFillIcon.svelte",
		},
		BoatIcon: {
			path: "lib/icons/BoatIcon.svelte",
		},
		BoneBrokenIcon: {
			path: "lib/icons/BoneBrokenIcon.svelte",
		},
		BoneFillIcon: {
			path: "lib/icons/BoneFillIcon.svelte",
		},
		BoneIcon: {
			path: "lib/icons/BoneIcon.svelte",
		},
		BookmarkFillIcon: {
			path: "lib/icons/BookmarkFillIcon.svelte",
		},
		BookmarkIcon: {
			path: "lib/icons/BookmarkIcon.svelte",
		},
		BowlFillIcon: {
			path: "lib/icons/BowlFillIcon.svelte",
		},
		BowlIcon: {
			path: "lib/icons/BowlIcon.svelte",
		},
		BrailleFillIcon: {
			path: "lib/icons/BrailleFillIcon.svelte",
		},
		BrailleIcon: {
			path: "lib/icons/BrailleIcon.svelte",
		},
		BranchingIcon: {
			path: "lib/icons/BranchingIcon.svelte",
		},
		BriefcaseClockFillIcon: {
			path: "lib/icons/BriefcaseClockFillIcon.svelte",
		},
		BriefcaseClockIcon: {
			path: "lib/icons/BriefcaseClockIcon.svelte",
		},
		BriefcaseFillIcon: {
			path: "lib/icons/BriefcaseFillIcon.svelte",
		},
		BriefcaseIcon: {
			path: "lib/icons/BriefcaseIcon.svelte",
		},
		BroadcastIcon: {
			path: "lib/icons/BroadcastIcon.svelte",
		},
		BroadcastMinusCircleFillIcon: {
			path: "lib/icons/BroadcastMinusCircleFillIcon.svelte",
		},
		BroadcastMinusCircleIcon: {
			path: "lib/icons/BroadcastMinusCircleIcon.svelte",
		},
		BroadcastPlusCircleFillIcon: {
			path: "lib/icons/BroadcastPlusCircleFillIcon.svelte",
		},
		BroadcastPlusCircleIcon: {
			path: "lib/icons/BroadcastPlusCircleIcon.svelte",
		},
		BubbleChartFillIcon: {
			path: "lib/icons/BubbleChartFillIcon.svelte",
		},
		BubbleChartIcon: {
			path: "lib/icons/BubbleChartIcon.svelte",
		},
		BucketFillIcon: {
			path: "lib/icons/BucketFillIcon.svelte",
		},
		BucketIcon: {
			path: "lib/icons/BucketIcon.svelte",
		},
		BucketMopFillIcon: {
			path: "lib/icons/BucketMopFillIcon.svelte",
		},
		BucketMopIcon: {
			path: "lib/icons/BucketMopIcon.svelte",
		},
		BugFillIcon: {
			path: "lib/icons/BugFillIcon.svelte",
		},
		BugIcon: {
			path: "lib/icons/BugIcon.svelte",
		},
		Buldings2FillIcon: {
			path: "lib/icons/Buldings2FillIcon.svelte",
		},
		Buldings2Icon: {
			path: "lib/icons/Buldings2Icon.svelte",
		},
		Buldings3FillIcon: {
			path: "lib/icons/Buldings3FillIcon.svelte",
		},
		Buldings3Icon: {
			path: "lib/icons/Buldings3Icon.svelte",
		},
		BulletListIcon: {
			path: "lib/icons/BulletListIcon.svelte",
		},
		BusFillIcon: {
			path: "lib/icons/BusFillIcon.svelte",
		},
		BusIcon: {
			path: "lib/icons/BusIcon.svelte",
		},
		CalculatorFillIcon: {
			path: "lib/icons/CalculatorFillIcon.svelte",
		},
		CalculatorIcon: {
			path: "lib/icons/CalculatorIcon.svelte",
		},
		CalendarFillIcon: {
			path: "lib/icons/CalendarFillIcon.svelte",
		},
		CalendarIcon: {
			path: "lib/icons/CalendarIcon.svelte",
		},
		CameraFillIcon: {
			path: "lib/icons/CameraFillIcon.svelte",
		},
		CameraIcon: {
			path: "lib/icons/CameraIcon.svelte",
		},
		CameraTriangleFillIcon: {
			path: "lib/icons/CameraTriangleFillIcon.svelte",
		},
		CameraTriangleIcon: {
			path: "lib/icons/CameraTriangleIcon.svelte",
		},
		CandleFillIcon: {
			path: "lib/icons/CandleFillIcon.svelte",
		},
		CandleIcon: {
			path: "lib/icons/CandleIcon.svelte",
		},
		CaptionsFillIcon: {
			path: "lib/icons/CaptionsFillIcon.svelte",
		},
		CaptionsIcon: {
			path: "lib/icons/CaptionsIcon.svelte",
		},
		CarFillIcon: {
			path: "lib/icons/CarFillIcon.svelte",
		},
		CarIcon: {
			path: "lib/icons/CarIcon.svelte",
		},
		CardFillIcon: {
			path: "lib/icons/CardFillIcon.svelte",
		},
		CardIcon: {
			path: "lib/icons/CardIcon.svelte",
		},
		CaretDownCircleFillIcon: {
			path: "lib/icons/CaretDownCircleFillIcon.svelte",
		},
		CaretDownCircleIcon: {
			path: "lib/icons/CaretDownCircleIcon.svelte",
		},
		CaretDownFillIcon: {
			path: "lib/icons/CaretDownFillIcon.svelte",
		},
		CaretDownIcon: {
			path: "lib/icons/CaretDownIcon.svelte",
		},
		CaretLeftCircleFillIcon: {
			path: "lib/icons/CaretLeftCircleFillIcon.svelte",
		},
		CaretLeftCircleIcon: {
			path: "lib/icons/CaretLeftCircleIcon.svelte",
		},
		CaretLeftFillIcon: {
			path: "lib/icons/CaretLeftFillIcon.svelte",
		},
		CaretLeftIcon: {
			path: "lib/icons/CaretLeftIcon.svelte",
		},
		CaretLeftRightFillIcon: {
			path: "lib/icons/CaretLeftRightFillIcon.svelte",
		},
		CaretLeftRightIcon: {
			path: "lib/icons/CaretLeftRightIcon.svelte",
		},
		CaretRightCircleFillIcon: {
			path: "lib/icons/CaretRightCircleFillIcon.svelte",
		},
		CaretRightCircleIcon: {
			path: "lib/icons/CaretRightCircleIcon.svelte",
		},
		CaretRightFillIcon: {
			path: "lib/icons/CaretRightFillIcon.svelte",
		},
		CaretRightIcon: {
			path: "lib/icons/CaretRightIcon.svelte",
		},
		CaretUpCircleFillIcon: {
			path: "lib/icons/CaretUpCircleFillIcon.svelte",
		},
		CaretUpCircleIcon: {
			path: "lib/icons/CaretUpCircleIcon.svelte",
		},
		CaretUpDownFillIcon: {
			path: "lib/icons/CaretUpDownFillIcon.svelte",
		},
		CaretUpDownFilledDownIcon: {
			path: "lib/icons/CaretUpDownFilledDownIcon.svelte",
		},
		CaretUpDownFilledUpIcon: {
			path: "lib/icons/CaretUpDownFilledUpIcon.svelte",
		},
		CaretUpDownIcon: {
			path: "lib/icons/CaretUpDownIcon.svelte",
		},
		CaretUpFillIcon: {
			path: "lib/icons/CaretUpFillIcon.svelte",
		},
		CaretUpIcon: {
			path: "lib/icons/CaretUpIcon.svelte",
		},
		ChangingRoomFillIcon: {
			path: "lib/icons/ChangingRoomFillIcon.svelte",
		},
		ChangingRoomIcon: {
			path: "lib/icons/ChangingRoomIcon.svelte",
		},
		Chat2FillIcon: {
			path: "lib/icons/Chat2FillIcon.svelte",
		},
		Chat2Icon: {
			path: "lib/icons/Chat2Icon.svelte",
		},
		ChatCheckmarkFillIcon: {
			path: "lib/icons/ChatCheckmarkFillIcon.svelte",
		},
		ChatCheckmarkIcon: {
			path: "lib/icons/ChatCheckmarkIcon.svelte",
		},
		ChatElipsisFillIcon: {
			path: "lib/icons/ChatElipsisFillIcon.svelte",
		},
		ChatElipsisIcon: {
			path: "lib/icons/ChatElipsisIcon.svelte",
		},
		ChatExclamationmarkFillIcon: {
			path: "lib/icons/ChatExclamationmarkFillIcon.svelte",
		},
		ChatExclamationmarkIcon: {
			path: "lib/icons/ChatExclamationmarkIcon.svelte",
		},
		ChatFillIcon: {
			path: "lib/icons/ChatFillIcon.svelte",
		},
		ChatIcon: {
			path: "lib/icons/ChatIcon.svelte",
		},
		CheckmarkCircleFillIcon: {
			path: "lib/icons/CheckmarkCircleFillIcon.svelte",
		},
		CheckmarkCircleIcon: {
			path: "lib/icons/CheckmarkCircleIcon.svelte",
		},
		CheckmarkIcon: {
			path: "lib/icons/CheckmarkIcon.svelte",
		},
		ChefHatFillIcon: {
			path: "lib/icons/ChefHatFillIcon.svelte",
		},
		ChefHatIcon: {
			path: "lib/icons/ChefHatIcon.svelte",
		},
		ChevronDownCircleFillIcon: {
			path: "lib/icons/ChevronDownCircleFillIcon.svelte",
		},
		ChevronDownCircleIcon: {
			path: "lib/icons/ChevronDownCircleIcon.svelte",
		},
		ChevronDownDoubleCircleFillIcon: {
			path: "lib/icons/ChevronDownDoubleCircleFillIcon.svelte",
		},
		ChevronDownDoubleCircleIcon: {
			path: "lib/icons/ChevronDownDoubleCircleIcon.svelte",
		},
		ChevronDownDoubleIcon: {
			path: "lib/icons/ChevronDownDoubleIcon.svelte",
		},
		ChevronDownIcon: {
			path: "lib/icons/ChevronDownIcon.svelte",
		},
		ChevronLeftCircleFillIcon: {
			path: "lib/icons/ChevronLeftCircleFillIcon.svelte",
		},
		ChevronLeftCircleIcon: {
			path: "lib/icons/ChevronLeftCircleIcon.svelte",
		},
		ChevronLeftDoubleCircleFillIcon: {
			path: "lib/icons/ChevronLeftDoubleCircleFillIcon.svelte",
		},
		ChevronLeftDoubleCircleIcon: {
			path: "lib/icons/ChevronLeftDoubleCircleIcon.svelte",
		},
		ChevronLeftDoubleIcon: {
			path: "lib/icons/ChevronLeftDoubleIcon.svelte",
		},
		ChevronLeftFirstIcon: {
			path: "lib/icons/ChevronLeftFirstIcon.svelte",
		},
		ChevronLeftIcon: {
			path: "lib/icons/ChevronLeftIcon.svelte",
		},
		ChevronRightCircleFillIcon: {
			path: "lib/icons/ChevronRightCircleFillIcon.svelte",
		},
		ChevronRightCircleIcon: {
			path: "lib/icons/ChevronRightCircleIcon.svelte",
		},
		ChevronRightDoubleCircleFillIcon: {
			path: "lib/icons/ChevronRightDoubleCircleFillIcon.svelte",
		},
		ChevronRightDoubleCircleIcon: {
			path: "lib/icons/ChevronRightDoubleCircleIcon.svelte",
		},
		ChevronRightDoubleIcon: {
			path: "lib/icons/ChevronRightDoubleIcon.svelte",
		},
		ChevronRightIcon: {
			path: "lib/icons/ChevronRightIcon.svelte",
		},
		ChevronRightLastIcon: {
			path: "lib/icons/ChevronRightLastIcon.svelte",
		},
		ChevronUpCircleFillIcon: {
			path: "lib/icons/ChevronUpCircleFillIcon.svelte",
		},
		ChevronUpCircleIcon: {
			path: "lib/icons/ChevronUpCircleIcon.svelte",
		},
		ChevronUpDoubleCircleFillIcon: {
			path: "lib/icons/ChevronUpDoubleCircleFillIcon.svelte",
		},
		ChevronUpDoubleCircleIcon: {
			path: "lib/icons/ChevronUpDoubleCircleIcon.svelte",
		},
		ChevronUpDoubleIcon: {
			path: "lib/icons/ChevronUpDoubleIcon.svelte",
		},
		ChevronUpDownIcon: {
			path: "lib/icons/ChevronUpDownIcon.svelte",
		},
		ChevronUpIcon: {
			path: "lib/icons/ChevronUpIcon.svelte",
		},
		ChildEyesFillIcon: {
			path: "lib/icons/ChildEyesFillIcon.svelte",
		},
		ChildEyesIcon: {
			path: "lib/icons/ChildEyesIcon.svelte",
		},
		CigaretteFillIcon: {
			path: "lib/icons/CigaretteFillIcon.svelte",
		},
		CigaretteIcon: {
			path: "lib/icons/CigaretteIcon.svelte",
		},
		CircleBrokenIcon: {
			path: "lib/icons/CircleBrokenIcon.svelte",
		},
		CircleSlashFillIcon: {
			path: "lib/icons/CircleSlashFillIcon.svelte",
		},
		CircleSlashIcon: {
			path: "lib/icons/CircleSlashIcon.svelte",
		},
		ClipboardFillIcon: {
			path: "lib/icons/ClipboardFillIcon.svelte",
		},
		ClipboardIcon: {
			path: "lib/icons/ClipboardIcon.svelte",
		},
		ClockDashedIcon: {
			path: "lib/icons/ClockDashedIcon.svelte",
		},
		ClockFillIcon: {
			path: "lib/icons/ClockFillIcon.svelte",
		},
		ClockIcon: {
			path: "lib/icons/ClockIcon.svelte",
		},
		ClothingHangerFillIcon: {
			path: "lib/icons/ClothingHangerFillIcon.svelte",
		},
		ClothingHangerIcon: {
			path: "lib/icons/ClothingHangerIcon.svelte",
		},
		CloudDownFillIcon: {
			path: "lib/icons/CloudDownFillIcon.svelte",
		},
		CloudDownIcon: {
			path: "lib/icons/CloudDownIcon.svelte",
		},
		CloudFillIcon: {
			path: "lib/icons/CloudFillIcon.svelte",
		},
		CloudIcon: {
			path: "lib/icons/CloudIcon.svelte",
		},
		CloudSlashFillIcon: {
			path: "lib/icons/CloudSlashFillIcon.svelte",
		},
		CloudSlashIcon: {
			path: "lib/icons/CloudSlashIcon.svelte",
		},
		CloudUpFillIcon: {
			path: "lib/icons/CloudUpFillIcon.svelte",
		},
		CloudUpIcon: {
			path: "lib/icons/CloudUpIcon.svelte",
		},
		CodeIcon: {
			path: "lib/icons/CodeIcon.svelte",
		},
		CoffeeFillIcon: {
			path: "lib/icons/CoffeeFillIcon.svelte",
		},
		CoffeeIcon: {
			path: "lib/icons/CoffeeIcon.svelte",
		},
		CogFillIcon: {
			path: "lib/icons/CogFillIcon.svelte",
		},
		CogIcon: {
			path: "lib/icons/CogIcon.svelte",
		},
		CogRotationFillIcon: {
			path: "lib/icons/CogRotationFillIcon.svelte",
		},
		CogRotationIcon: {
			path: "lib/icons/CogRotationIcon.svelte",
		},
		Combifridge1FillIcon: {
			path: "lib/icons/Combifridge1FillIcon.svelte",
		},
		Combifridge1Icon: {
			path: "lib/icons/Combifridge1Icon.svelte",
		},
		Combifridge2FillIcon: {
			path: "lib/icons/Combifridge2FillIcon.svelte",
		},
		Combifridge2Icon: {
			path: "lib/icons/Combifridge2Icon.svelte",
		},
		CompassFillIcon: {
			path: "lib/icons/CompassFillIcon.svelte",
		},
		CompassIcon: {
			path: "lib/icons/CompassIcon.svelte",
		},
		ComponentFillIcon: {
			path: "lib/icons/ComponentFillIcon.svelte",
		},
		ComponentIcon: {
			path: "lib/icons/ComponentIcon.svelte",
		},
		CurrencyExchangeIcon: {
			path: "lib/icons/CurrencyExchangeIcon.svelte",
		},
		CutleryFillIcon: {
			path: "lib/icons/CutleryFillIcon.svelte",
		},
		CutleryIcon: {
			path: "lib/icons/CutleryIcon.svelte",
		},
		DatabaseFillIcon: {
			path: "lib/icons/DatabaseFillIcon.svelte",
		},
		DatabaseIcon: {
			path: "lib/icons/DatabaseIcon.svelte",
		},
		Density1FillIcon: {
			path: "lib/icons/Density1FillIcon.svelte",
		},
		Density1Icon: {
			path: "lib/icons/Density1Icon.svelte",
		},
		Density2FillIcon: {
			path: "lib/icons/Density2FillIcon.svelte",
		},
		Density2Icon: {
			path: "lib/icons/Density2Icon.svelte",
		},
		Density3Icon: {
			path: "lib/icons/Density3Icon.svelte",
		},
		DishwasherFillIcon: {
			path: "lib/icons/DishwasherFillIcon.svelte",
		},
		DishwasherIcon: {
			path: "lib/icons/DishwasherIcon.svelte",
		},
		DivideIcon: {
			path: "lib/icons/DivideIcon.svelte",
		},
		DocPencilFillIcon: {
			path: "lib/icons/DocPencilFillIcon.svelte",
		},
		DocPencilIcon: {
			path: "lib/icons/DocPencilIcon.svelte",
		},
		DogFillIcon: {
			path: "lib/icons/DogFillIcon.svelte",
		},
		DogHarnessFillIcon: {
			path: "lib/icons/DogHarnessFillIcon.svelte",
		},
		DogHarnessIcon: {
			path: "lib/icons/DogHarnessIcon.svelte",
		},
		DogIcon: {
			path: "lib/icons/DogIcon.svelte",
		},
		DonutChartFillIcon: {
			path: "lib/icons/DonutChartFillIcon.svelte",
		},
		DonutChartIcon: {
			path: "lib/icons/DonutChartIcon.svelte",
		},
		DonutsFillIcon: {
			path: "lib/icons/DonutsFillIcon.svelte",
		},
		DonutsIcon: {
			path: "lib/icons/DonutsIcon.svelte",
		},
		DoorFillIcon: {
			path: "lib/icons/DoorFillIcon.svelte",
		},
		DoorIcon: {
			path: "lib/icons/DoorIcon.svelte",
		},
		DoorOpenFillIcon: {
			path: "lib/icons/DoorOpenFillIcon.svelte",
		},
		DoorOpenIcon: {
			path: "lib/icons/DoorOpenIcon.svelte",
		},
		DownloadIcon: {
			path: "lib/icons/DownloadIcon.svelte",
		},
		DragHorizontalIcon: {
			path: "lib/icons/DragHorizontalIcon.svelte",
		},
		DragVerticalIcon: {
			path: "lib/icons/DragVerticalIcon.svelte",
		},
		EarFillIcon: {
			path: "lib/icons/EarFillIcon.svelte",
		},
		EarIcon: {
			path: "lib/icons/EarIcon.svelte",
		},
		EarSlashFillIcon: {
			path: "lib/icons/EarSlashFillIcon.svelte",
		},
		EarSlashIcon: {
			path: "lib/icons/EarSlashIcon.svelte",
		},
		EarSoundwavesFillIcon: {
			path: "lib/icons/EarSoundwavesFillIcon.svelte",
		},
		EarSoundwavesIcon: {
			path: "lib/icons/EarSoundwavesIcon.svelte",
		},
		EarthFillIcon: {
			path: "lib/icons/EarthFillIcon.svelte",
		},
		EarthIcon: {
			path: "lib/icons/EarthIcon.svelte",
		},
		ElevatorFillIcon: {
			path: "lib/icons/ElevatorFillIcon.svelte",
		},
		ElevatorIcon: {
			path: "lib/icons/ElevatorIcon.svelte",
		},
		EnterIcon: {
			path: "lib/icons/EnterIcon.svelte",
		},
		EnvelopeClosedFillIcon: {
			path: "lib/icons/EnvelopeClosedFillIcon.svelte",
		},
		EnvelopeClosedIcon: {
			path: "lib/icons/EnvelopeClosedIcon.svelte",
		},
		EnvelopeOpenFillIcon: {
			path: "lib/icons/EnvelopeOpenFillIcon.svelte",
		},
		EnvelopeOpenIcon: {
			path: "lib/icons/EnvelopeOpenIcon.svelte",
		},
		EqualsIcon: {
			path: "lib/icons/EqualsIcon.svelte",
		},
		EraserFillIcon: {
			path: "lib/icons/EraserFillIcon.svelte",
		},
		EraserIcon: {
			path: "lib/icons/EraserIcon.svelte",
		},
		EscalatorIcon: {
			path: "lib/icons/EscalatorIcon.svelte",
		},
		EthernetIcon: {
			path: "lib/icons/EthernetIcon.svelte",
		},
		ExclamationmarkIcon: {
			path: "lib/icons/ExclamationmarkIcon.svelte",
		},
		ExclamationmarkTriangleFillIcon: {
			path: "lib/icons/ExclamationmarkTriangleFillIcon.svelte",
		},
		ExclamationmarkTriangleIcon: {
			path: "lib/icons/ExclamationmarkTriangleIcon.svelte",
		},
		ExpandIcon: {
			path: "lib/icons/ExpandIcon.svelte",
		},
		ExternalLinkFillIcon: {
			path: "lib/icons/ExternalLinkFillIcon.svelte",
		},
		ExternalLinkIcon: {
			path: "lib/icons/ExternalLinkIcon.svelte",
		},
		EyeClosedIcon: {
			path: "lib/icons/EyeClosedIcon.svelte",
		},
		EyeFillIcon: {
			path: "lib/icons/EyeFillIcon.svelte",
		},
		EyeIcon: {
			path: "lib/icons/EyeIcon.svelte",
		},
		EyeObfuscatedFillIcon: {
			path: "lib/icons/EyeObfuscatedFillIcon.svelte",
		},
		EyeObfuscatedIcon: {
			path: "lib/icons/EyeObfuscatedIcon.svelte",
		},
		EyeSlashFillIcon: {
			path: "lib/icons/EyeSlashFillIcon.svelte",
		},
		EyeSlashIcon: {
			path: "lib/icons/EyeSlashIcon.svelte",
		},
		EyeWithPupilFillIcon: {
			path: "lib/icons/EyeWithPupilFillIcon.svelte",
		},
		EyeWithPupilIcon: {
			path: "lib/icons/EyeWithPupilIcon.svelte",
		},
		FaceFillIcon: {
			path: "lib/icons/FaceFillIcon.svelte",
		},
		FaceFrownFillIcon: {
			path: "lib/icons/FaceFrownFillIcon.svelte",
		},
		FaceFrownIcon: {
			path: "lib/icons/FaceFrownIcon.svelte",
		},
		FaceIcon: {
			path: "lib/icons/FaceIcon.svelte",
		},
		FaceSmileFillIcon: {
			path: "lib/icons/FaceSmileFillIcon.svelte",
		},
		FaceSmileIcon: {
			path: "lib/icons/FaceSmileIcon.svelte",
		},
		FeedingBottleFillIcon: {
			path: "lib/icons/FeedingBottleFillIcon.svelte",
		},
		FeedingBottleIcon: {
			path: "lib/icons/FeedingBottleIcon.svelte",
		},
		FigureCombinationFillIcon: {
			path: "lib/icons/FigureCombinationFillIcon.svelte",
		},
		FigureCombinationIcon: {
			path: "lib/icons/FigureCombinationIcon.svelte",
		},
		FigureFillIcon: {
			path: "lib/icons/FigureFillIcon.svelte",
		},
		FigureIcon: {
			path: "lib/icons/FigureIcon.svelte",
		},
		FigureInwardFillIcon: {
			path: "lib/icons/FigureInwardFillIcon.svelte",
		},
		FigureInwardIcon: {
			path: "lib/icons/FigureInwardIcon.svelte",
		},
		FigureOutwardFillIcon: {
			path: "lib/icons/FigureOutwardFillIcon.svelte",
		},
		FigureOutwardIcon: {
			path: "lib/icons/FigureOutwardIcon.svelte",
		},
		FileCheckmarkFillIcon: {
			path: "lib/icons/FileCheckmarkFillIcon.svelte",
		},
		FileCheckmarkIcon: {
			path: "lib/icons/FileCheckmarkIcon.svelte",
		},
		FileCodeFillIcon: {
			path: "lib/icons/FileCodeFillIcon.svelte",
		},
		FileCodeIcon: {
			path: "lib/icons/FileCodeIcon.svelte",
		},
		FileCsvFillIcon: {
			path: "lib/icons/FileCsvFillIcon.svelte",
		},
		FileCsvIcon: {
			path: "lib/icons/FileCsvIcon.svelte",
		},
		FileExcelFillIcon: {
			path: "lib/icons/FileExcelFillIcon.svelte",
		},
		FileExcelIcon: {
			path: "lib/icons/FileExcelIcon.svelte",
		},
		FileExportFillIcon: {
			path: "lib/icons/FileExportFillIcon.svelte",
		},
		FileExportIcon: {
			path: "lib/icons/FileExportIcon.svelte",
		},
		FileFillIcon: {
			path: "lib/icons/FileFillIcon.svelte",
		},
		FileIcon: {
			path: "lib/icons/FileIcon.svelte",
		},
		FileImageFillIcon: {
			path: "lib/icons/FileImageFillIcon.svelte",
		},
		FileImageIcon: {
			path: "lib/icons/FileImageIcon.svelte",
		},
		FileImportFillIcon: {
			path: "lib/icons/FileImportFillIcon.svelte",
		},
		FileImportIcon: {
			path: "lib/icons/FileImportIcon.svelte",
		},
		FileJsonFillIcon: {
			path: "lib/icons/FileJsonFillIcon.svelte",
		},
		FileJsonIcon: {
			path: "lib/icons/FileJsonIcon.svelte",
		},
		FileLoadingFillIcon: {
			path: "lib/icons/FileLoadingFillIcon.svelte",
		},
		FileLoadingIcon: {
			path: "lib/icons/FileLoadingIcon.svelte",
		},
		FileParagraphFillIcon: {
			path: "lib/icons/FileParagraphFillIcon.svelte",
		},
		FileParagraphIcon: {
			path: "lib/icons/FileParagraphIcon.svelte",
		},
		FilePdfFillIcon: {
			path: "lib/icons/FilePdfFillIcon.svelte",
		},
		FilePdfIcon: {
			path: "lib/icons/FilePdfIcon.svelte",
		},
		FilePlusFillIcon: {
			path: "lib/icons/FilePlusFillIcon.svelte",
		},
		FilePlusIcon: {
			path: "lib/icons/FilePlusIcon.svelte",
		},
		FileResetFillIcon: {
			path: "lib/icons/FileResetFillIcon.svelte",
		},
		FileResetIcon: {
			path: "lib/icons/FileResetIcon.svelte",
		},
		FileSearchFillIcon: {
			path: "lib/icons/FileSearchFillIcon.svelte",
		},
		FileSearchIcon: {
			path: "lib/icons/FileSearchIcon.svelte",
		},
		FileShredderFillIcon: {
			path: "lib/icons/FileShredderFillIcon.svelte",
		},
		FileShredderIcon: {
			path: "lib/icons/FileShredderIcon.svelte",
		},
		FileTextFillIcon: {
			path: "lib/icons/FileTextFillIcon.svelte",
		},
		FileTextIcon: {
			path: "lib/icons/FileTextIcon.svelte",
		},
		FileWordFillIcon: {
			path: "lib/icons/FileWordFillIcon.svelte",
		},
		FileWordIcon: {
			path: "lib/icons/FileWordIcon.svelte",
		},
		FileXMarkFillIcon: {
			path: "lib/icons/FileXMarkFillIcon.svelte",
		},
		FileXMarkIcon: {
			path: "lib/icons/FileXMarkIcon.svelte",
		},
		FilesFillIcon: {
			path: "lib/icons/FilesFillIcon.svelte",
		},
		FilesIcon: {
			path: "lib/icons/FilesIcon.svelte",
		},
		FilterIcon: {
			path: "lib/icons/FilterIcon.svelte",
		},
		FingerButtonFillIcon: {
			path: "lib/icons/FingerButtonFillIcon.svelte",
		},
		FingerButtonIcon: {
			path: "lib/icons/FingerButtonIcon.svelte",
		},
		FingerMobileFillIcon: {
			path: "lib/icons/FingerMobileFillIcon.svelte",
		},
		FingerMobileIcon: {
			path: "lib/icons/FingerMobileIcon.svelte",
		},
		FirstAidFillIcon: {
			path: "lib/icons/FirstAidFillIcon.svelte",
		},
		FirstAidIcon: {
			path: "lib/icons/FirstAidIcon.svelte",
		},
		FirstAidKitFillIcon: {
			path: "lib/icons/FirstAidKitFillIcon.svelte",
		},
		FirstAidKitIcon: {
			path: "lib/icons/FirstAidKitIcon.svelte",
		},
		FlagCrossFillIcon: {
			path: "lib/icons/FlagCrossFillIcon.svelte",
		},
		FlagCrossIcon: {
			path: "lib/icons/FlagCrossIcon.svelte",
		},
		FloppydiskFillIcon: {
			path: "lib/icons/FloppydiskFillIcon.svelte",
		},
		FloppydiskIcon: {
			path: "lib/icons/FloppydiskIcon.svelte",
		},
		FlowerFillIcon: {
			path: "lib/icons/FlowerFillIcon.svelte",
		},
		FlowerIcon: {
			path: "lib/icons/FlowerIcon.svelte",
		},
		FlowerPensionFillIcon: {
			path: "lib/icons/FlowerPensionFillIcon.svelte",
		},
		FlowerPensionIcon: {
			path: "lib/icons/FlowerPensionIcon.svelte",
		},
		FlowerPetalFallingFillIcon: {
			path: "lib/icons/FlowerPetalFallingFillIcon.svelte",
		},
		FlowerPetalFallingIcon: {
			path: "lib/icons/FlowerPetalFallingIcon.svelte",
		},
		FlowerPetalsFillIcon: {
			path: "lib/icons/FlowerPetalsFillIcon.svelte",
		},
		FlowerPetalsIcon: {
			path: "lib/icons/FlowerPetalsIcon.svelte",
		},
		FolderFileFillIcon: {
			path: "lib/icons/FolderFileFillIcon.svelte",
		},
		FolderFileIcon: {
			path: "lib/icons/FolderFileIcon.svelte",
		},
		FolderFillIcon: {
			path: "lib/icons/FolderFillIcon.svelte",
		},
		FolderIcon: {
			path: "lib/icons/FolderIcon.svelte",
		},
		FolderMinusFillIcon: {
			path: "lib/icons/FolderMinusFillIcon.svelte",
		},
		FolderMinusIcon: {
			path: "lib/icons/FolderMinusIcon.svelte",
		},
		FolderPlusFillIcon: {
			path: "lib/icons/FolderPlusFillIcon.svelte",
		},
		FolderPlusIcon: {
			path: "lib/icons/FolderPlusIcon.svelte",
		},
		ForkFillIcon: {
			path: "lib/icons/ForkFillIcon.svelte",
		},
		ForkIcon: {
			path: "lib/icons/ForkIcon.svelte",
		},
		ForwardFillIcon: {
			path: "lib/icons/ForwardFillIcon.svelte",
		},
		ForwardIcon: {
			path: "lib/icons/ForwardIcon.svelte",
		},
		FreezerFillIcon: {
			path: "lib/icons/FreezerFillIcon.svelte",
		},
		FreezerIcon: {
			path: "lib/icons/FreezerIcon.svelte",
		},
		FunnelFillIcon: {
			path: "lib/icons/FunnelFillIcon.svelte",
		},
		FunnelIcon: {
			path: "lib/icons/FunnelIcon.svelte",
		},
		GavelFillIcon: {
			path: "lib/icons/GavelFillIcon.svelte",
		},
		GavelIcon: {
			path: "lib/icons/GavelIcon.svelte",
		},
		GavelSoundBlockFillIcon: {
			path: "lib/icons/GavelSoundBlockFillIcon.svelte",
		},
		GavelSoundBlockIcon: {
			path: "lib/icons/GavelSoundBlockIcon.svelte",
		},
		GlassFillIcon: {
			path: "lib/icons/GlassFillIcon.svelte",
		},
		GlassIcon: {
			path: "lib/icons/GlassIcon.svelte",
		},
		GlassesFillIcon: {
			path: "lib/icons/GlassesFillIcon.svelte",
		},
		GlassesIcon: {
			path: "lib/icons/GlassesIcon.svelte",
		},
		GlobeFillIcon: {
			path: "lib/icons/GlobeFillIcon.svelte",
		},
		GlobeIcon: {
			path: "lib/icons/GlobeIcon.svelte",
		},
		GlobeSlashFillIcon: {
			path: "lib/icons/GlobeSlashFillIcon.svelte",
		},
		GlobeSlashIcon: {
			path: "lib/icons/GlobeSlashIcon.svelte",
		},
		HandBandageFillIcon: {
			path: "lib/icons/HandBandageFillIcon.svelte",
		},
		HandBandageIcon: {
			path: "lib/icons/HandBandageIcon.svelte",
		},
		HandFingerFillIcon: {
			path: "lib/icons/HandFingerFillIcon.svelte",
		},
		HandFingerIcon: {
			path: "lib/icons/HandFingerIcon.svelte",
		},
		HandHeartFillIcon: {
			path: "lib/icons/HandHeartFillIcon.svelte",
		},
		HandHeartIcon: {
			path: "lib/icons/HandHeartIcon.svelte",
		},
		HandKnotFilledIcon: {
			path: "lib/icons/HandKnotFilledIcon.svelte",
		},
		HandKnotIcon: {
			path: "lib/icons/HandKnotIcon.svelte",
		},
		HandShakeHeartFillIcon: {
			path: "lib/icons/HandShakeHeartFillIcon.svelte",
		},
		HandShakeHeartIcon: {
			path: "lib/icons/HandShakeHeartIcon.svelte",
		},
		HandshakeFillIcon: {
			path: "lib/icons/HandshakeFillIcon.svelte",
		},
		HandshakeIcon: {
			path: "lib/icons/HandshakeIcon.svelte",
		},
		HangerIcon: {
			path: "lib/icons/HangerIcon.svelte",
		},
		HardHatFillIcon: {
			path: "lib/icons/HardHatFillIcon.svelte",
		},
		HardHatIcon: {
			path: "lib/icons/HardHatIcon.svelte",
		},
		HashtagIcon: {
			path: "lib/icons/HashtagIcon.svelte",
		},
		HatSchoolFillIcon: {
			path: "lib/icons/HatSchoolFillIcon.svelte",
		},
		HatSchoolIcon: {
			path: "lib/icons/HatSchoolIcon.svelte",
		},
		HddDownFillIcon: {
			path: "lib/icons/HddDownFillIcon.svelte",
		},
		HddDownIcon: {
			path: "lib/icons/HddDownIcon.svelte",
		},
		HddUpFillIcon: {
			path: "lib/icons/HddUpFillIcon.svelte",
		},
		HddUpIcon: {
			path: "lib/icons/HddUpIcon.svelte",
		},
		HeadCloudFillIcon: {
			path: "lib/icons/HeadCloudFillIcon.svelte",
		},
		HeadCloudIcon: {
			path: "lib/icons/HeadCloudIcon.svelte",
		},
		HeadFillIcon: {
			path: "lib/icons/HeadFillIcon.svelte",
		},
		HeadHeartFillIcon: {
			path: "lib/icons/HeadHeartFillIcon.svelte",
		},
		HeadHeartIcon: {
			path: "lib/icons/HeadHeartIcon.svelte",
		},
		HeadIcon: {
			path: "lib/icons/HeadIcon.svelte",
		},
		HearingLoopFillIcon: {
			path: "lib/icons/HearingLoopFillIcon.svelte",
		},
		HearingLoopIcon: {
			path: "lib/icons/HearingLoopIcon.svelte",
		},
		HearingLoopRadioFillIcon: {
			path: "lib/icons/HearingLoopRadioFillIcon.svelte",
		},
		HearingLoopRadioIcon: {
			path: "lib/icons/HearingLoopRadioIcon.svelte",
		},
		HeartBrokenFillIcon: {
			path: "lib/icons/HeartBrokenFillIcon.svelte",
		},
		HeartBrokenIcon: {
			path: "lib/icons/HeartBrokenIcon.svelte",
		},
		HeartFillIcon: {
			path: "lib/icons/HeartFillIcon.svelte",
		},
		HeartIcon: {
			path: "lib/icons/HeartIcon.svelte",
		},
		HexagonGridFillIcon: {
			path: "lib/icons/HexagonGridFillIcon.svelte",
		},
		HexagonGridIcon: {
			path: "lib/icons/HexagonGridIcon.svelte",
		},
		HikingTrailSignFillIcon: {
			path: "lib/icons/HikingTrailSignFillIcon.svelte",
		},
		HikingTrailSignIcon: {
			path: "lib/icons/HikingTrailSignIcon.svelte",
		},
		HospitalFillIcon: {
			path: "lib/icons/HospitalFillIcon.svelte",
		},
		HospitalIcon: {
			path: "lib/icons/HospitalIcon.svelte",
		},
		HourglassBottomFilledIcon: {
			path: "lib/icons/HourglassBottomFilledIcon.svelte",
		},
		HourglassIcon: {
			path: "lib/icons/HourglassIcon.svelte",
		},
		HourglassTopFilledIcon: {
			path: "lib/icons/HourglassTopFilledIcon.svelte",
		},
		HouseFillIcon: {
			path: "lib/icons/HouseFillIcon.svelte",
		},
		HouseHeartFillIcon: {
			path: "lib/icons/HouseHeartFillIcon.svelte",
		},
		HouseHeartIcon: {
			path: "lib/icons/HouseHeartIcon.svelte",
		},
		HouseIcon: {
			path: "lib/icons/HouseIcon.svelte",
		},
		ImageFillIcon: {
			path: "lib/icons/ImageFillIcon.svelte",
		},
		ImageIcon: {
			path: "lib/icons/ImageIcon.svelte",
		},
		InboxDownFillIcon: {
			path: "lib/icons/InboxDownFillIcon.svelte",
		},
		InboxDownIcon: {
			path: "lib/icons/InboxDownIcon.svelte",
		},
		InboxFillIcon: {
			path: "lib/icons/InboxFillIcon.svelte",
		},
		InboxIcon: {
			path: "lib/icons/InboxIcon.svelte",
		},
		InboxUpFillIcon: {
			path: "lib/icons/InboxUpFillIcon.svelte",
		},
		InboxUpIcon: {
			path: "lib/icons/InboxUpIcon.svelte",
		},
		InformationIcon: {
			path: "lib/icons/InformationIcon.svelte",
		},
		InformationSquareFillIcon: {
			path: "lib/icons/InformationSquareFillIcon.svelte",
		},
		InformationSquareIcon: {
			path: "lib/icons/InformationSquareIcon.svelte",
		},
		IvFluidBagFillIcon: {
			path: "lib/icons/IvFluidBagFillIcon.svelte",
		},
		IvFluidBagIcon: {
			path: "lib/icons/IvFluidBagIcon.svelte",
		},
		KeyHorizontalFillIcon: {
			path: "lib/icons/KeyHorizontalFillIcon.svelte",
		},
		KeyHorizontalIcon: {
			path: "lib/icons/KeyHorizontalIcon.svelte",
		},
		KeyVerticalFillIcon: {
			path: "lib/icons/KeyVerticalFillIcon.svelte",
		},
		KeyVerticalIcon: {
			path: "lib/icons/KeyVerticalIcon.svelte",
		},
		KnifeFillIcon: {
			path: "lib/icons/KnifeFillIcon.svelte",
		},
		KnifeIcon: {
			path: "lib/icons/KnifeIcon.svelte",
		},
		KronerIcon: {
			path: "lib/icons/KronerIcon.svelte",
		},
		LanguageIcon: {
			path: "lib/icons/LanguageIcon.svelte",
		},
		LaptopFillIcon: {
			path: "lib/icons/LaptopFillIcon.svelte",
		},
		LaptopIcon: {
			path: "lib/icons/LaptopIcon.svelte",
		},
		LaptopTriangleFillIcon: {
			path: "lib/icons/LaptopTriangleFillIcon.svelte",
		},
		LaptopTriangleIcon: {
			path: "lib/icons/LaptopTriangleIcon.svelte",
		},
		LayerMinusFillIcon: {
			path: "lib/icons/LayerMinusFillIcon.svelte",
		},
		LayerMinusIcon: {
			path: "lib/icons/LayerMinusIcon.svelte",
		},
		LayersFillIcon: {
			path: "lib/icons/LayersFillIcon.svelte",
		},
		LayersIcon: {
			path: "lib/icons/LayersIcon.svelte",
		},
		LayersPlusFillIcon: {
			path: "lib/icons/LayersPlusFillIcon.svelte",
		},
		LayersPlusIcon: {
			path: "lib/icons/LayersPlusIcon.svelte",
		},
		LeaveIcon: {
			path: "lib/icons/LeaveIcon.svelte",
		},
		LightBulbFillIcon: {
			path: "lib/icons/LightBulbFillIcon.svelte",
		},
		LightBulbIcon: {
			path: "lib/icons/LightBulbIcon.svelte",
		},
		LightningFillIcon: {
			path: "lib/icons/LightningFillIcon.svelte",
		},
		LightningIcon: {
			path: "lib/icons/LightningIcon.svelte",
		},
		LineGraphDotIcon: {
			path: "lib/icons/LineGraphDotIcon.svelte",
		},
		LineGraphIcon: {
			path: "lib/icons/LineGraphIcon.svelte",
		},
		LineGraphStackedIcon: {
			path: "lib/icons/LineGraphStackedIcon.svelte",
		},
		LinkBrokenIcon: {
			path: "lib/icons/LinkBrokenIcon.svelte",
		},
		LinkIcon: {
			path: "lib/icons/LinkIcon.svelte",
		},
		MagnifyingGlassFillIcon: {
			path: "lib/icons/MagnifyingGlassFillIcon.svelte",
		},
		MagnifyingGlassIcon: {
			path: "lib/icons/MagnifyingGlassIcon.svelte",
		},
		MeasuringTapeFillIcon: {
			path: "lib/icons/MeasuringTapeFillIcon.svelte",
		},
		MeasuringTapeIcon: {
			path: "lib/icons/MeasuringTapeIcon.svelte",
		},
		MedicineBottleFillIcon: {
			path: "lib/icons/MedicineBottleFillIcon.svelte",
		},
		MedicineBottleIcon: {
			path: "lib/icons/MedicineBottleIcon.svelte",
		},
		MeetingLargeFillIcon: {
			path: "lib/icons/MeetingLargeFillIcon.svelte",
		},
		MeetingLargeIcon: {
			path: "lib/icons/MeetingLargeIcon.svelte",
		},
		MeetingSmallFillIcon: {
			path: "lib/icons/MeetingSmallFillIcon.svelte",
		},
		MeetingSmallIcon: {
			path: "lib/icons/MeetingSmallIcon.svelte",
		},
		MegaphoneFillIcon: {
			path: "lib/icons/MegaphoneFillIcon.svelte",
		},
		MegaphoneIcon: {
			path: "lib/icons/MegaphoneIcon.svelte",
		},
		MegaphoneSpeakingFillIcon: {
			path: "lib/icons/MegaphoneSpeakingFillIcon.svelte",
		},
		MegaphoneSpeakingIcon: {
			path: "lib/icons/MegaphoneSpeakingIcon.svelte",
		},
		MenuElipsisHorizontalCircleFillIcon: {
			path: "lib/icons/MenuElipsisHorizontalCircleFillIcon.svelte",
		},
		MenuElipsisHorizontalCircleIcon: {
			path: "lib/icons/MenuElipsisHorizontalCircleIcon.svelte",
		},
		MenuElipsisHorizontalIcon: {
			path: "lib/icons/MenuElipsisHorizontalIcon.svelte",
		},
		MenuElipsisHorizontalSquareFillIcon: {
			path: "lib/icons/MenuElipsisHorizontalSquareFillIcon.svelte",
		},
		MenuElipsisHorizontalSquareIcon: {
			path: "lib/icons/MenuElipsisHorizontalSquareIcon.svelte",
		},
		MenuElipsisVerticalCircleFillIcon: {
			path: "lib/icons/MenuElipsisVerticalCircleFillIcon.svelte",
		},
		MenuElipsisVerticalCircleIcon: {
			path: "lib/icons/MenuElipsisVerticalCircleIcon.svelte",
		},
		MenuElipsisVerticalIcon: {
			path: "lib/icons/MenuElipsisVerticalIcon.svelte",
		},
		MenuElipsisVerticalSquareFillIcon: {
			path: "lib/icons/MenuElipsisVerticalSquareFillIcon.svelte",
		},
		MenuElipsisVerticalSquareIcon: {
			path: "lib/icons/MenuElipsisVerticalSquareIcon.svelte",
		},
		MenuGridIcon: {
			path: "lib/icons/MenuGridIcon.svelte",
		},
		MenuHamburgerIcon: {
			path: "lib/icons/MenuHamburgerIcon.svelte",
		},
		MicrobeFillIcon: {
			path: "lib/icons/MicrobeFillIcon.svelte",
		},
		MicrobeIcon: {
			path: "lib/icons/MicrobeIcon.svelte",
		},
		MicrophoneFillIcon: {
			path: "lib/icons/MicrophoneFillIcon.svelte",
		},
		MicrophoneIcon: {
			path: "lib/icons/MicrophoneIcon.svelte",
		},
		MicrophoneSlashFillIcon: {
			path: "lib/icons/MicrophoneSlashFillIcon.svelte",
		},
		MicrophoneSlashIcon: {
			path: "lib/icons/MicrophoneSlashIcon.svelte",
		},
		MigrationIcon: {
			path: "lib/icons/MigrationIcon.svelte",
		},
		MinusCircleFillIcon: {
			path: "lib/icons/MinusCircleFillIcon.svelte",
		},
		MinusCircleIcon: {
			path: "lib/icons/MinusCircleIcon.svelte",
		},
		MinusIcon: {
			path: "lib/icons/MinusIcon.svelte",
		},
		MobileFillIcon: {
			path: "lib/icons/MobileFillIcon.svelte",
		},
		MobileIcon: {
			path: "lib/icons/MobileIcon.svelte",
		},
		MobileSmallFillIcon: {
			path: "lib/icons/MobileSmallFillIcon.svelte",
		},
		MobileSmallIcon: {
			path: "lib/icons/MobileSmallIcon.svelte",
		},
		MobileTriangleFillIcon: {
			path: "lib/icons/MobileTriangleFillIcon.svelte",
		},
		MobileTriangleIcon: {
			path: "lib/icons/MobileTriangleIcon.svelte",
		},
		MonitorFillIcon: {
			path: "lib/icons/MonitorFillIcon.svelte",
		},
		MonitorIcon: {
			path: "lib/icons/MonitorIcon.svelte",
		},
		MonitorTriangleFillIcon: {
			path: "lib/icons/MonitorTriangleFillIcon.svelte",
		},
		MonitorTriangleIcon: {
			path: "lib/icons/MonitorTriangleIcon.svelte",
		},
		MoonFillIcon: {
			path: "lib/icons/MoonFillIcon.svelte",
		},
		MoonIcon: {
			path: "lib/icons/MoonIcon.svelte",
		},
		MotorcycleFillIcon: {
			path: "lib/icons/MotorcycleFillIcon.svelte",
		},
		MotorcycleIcon: {
			path: "lib/icons/MotorcycleIcon.svelte",
		},
		MountainFillIcon: {
			path: "lib/icons/MountainFillIcon.svelte",
		},
		MountainIcon: {
			path: "lib/icons/MountainIcon.svelte",
		},
		MugFillIcon: {
			path: "lib/icons/MugFillIcon.svelte",
		},
		MugIcon: {
			path: "lib/icons/MugIcon.svelte",
		},
		MultiplyIcon: {
			path: "lib/icons/MultiplyIcon.svelte",
		},
		NewspaperFillIcon: {
			path: "lib/icons/NewspaperFillIcon.svelte",
		},
		NewspaperIcon: {
			path: "lib/icons/NewspaperIcon.svelte",
		},
		NoSmokingFillIcon: {
			path: "lib/icons/NoSmokingFillIcon.svelte",
		},
		NoSmokingIcon: {
			path: "lib/icons/NoSmokingIcon.svelte",
		},
		NokIcon: {
			path: "lib/icons/NokIcon.svelte",
		},
		NumberListIcon: {
			path: "lib/icons/NumberListIcon.svelte",
		},
		Over18FillIcon: {
			path: "lib/icons/Over18FillIcon.svelte",
		},
		Over18Icon: {
			path: "lib/icons/Over18Icon.svelte",
		},
		PackageFillIcon: {
			path: "lib/icons/PackageFillIcon.svelte",
		},
		PackageIcon: {
			path: "lib/icons/PackageIcon.svelte",
		},
		PadlockLockedFillIcon: {
			path: "lib/icons/PadlockLockedFillIcon.svelte",
		},
		PadlockLockedIcon: {
			path: "lib/icons/PadlockLockedIcon.svelte",
		},
		PadlockUnlockedFillIcon: {
			path: "lib/icons/PadlockUnlockedFillIcon.svelte",
		},
		PadlockUnlockedIcon: {
			path: "lib/icons/PadlockUnlockedIcon.svelte",
		},
		PaletteFillIcon: {
			path: "lib/icons/PaletteFillIcon.svelte",
		},
		PaletteIcon: {
			path: "lib/icons/PaletteIcon.svelte",
		},
		PaperclipIcon: {
			path: "lib/icons/PaperclipIcon.svelte",
		},
		PaperplaneFillIcon: {
			path: "lib/icons/PaperplaneFillIcon.svelte",
		},
		PaperplaneIcon: {
			path: "lib/icons/PaperplaneIcon.svelte",
		},
		ParagraphIcon: {
			path: "lib/icons/ParagraphIcon.svelte",
		},
		ParasolBeachFillIcon: {
			path: "lib/icons/ParasolBeachFillIcon.svelte",
		},
		ParasolBeachIcon: {
			path: "lib/icons/ParasolBeachIcon.svelte",
		},
		ParkingFillIcon: {
			path: "lib/icons/ParkingFillIcon.svelte",
		},
		ParkingIcon: {
			path: "lib/icons/ParkingIcon.svelte",
		},
		PassportFillIcon: {
			path: "lib/icons/PassportFillIcon.svelte",
		},
		PassportIcon: {
			path: "lib/icons/PassportIcon.svelte",
		},
		PasswordHiddenIcon: {
			path: "lib/icons/PasswordHiddenIcon.svelte",
		},
		PauseFillIcon: {
			path: "lib/icons/PauseFillIcon.svelte",
		},
		PauseIcon: {
			path: "lib/icons/PauseIcon.svelte",
		},
		PencilBoardFillIcon: {
			path: "lib/icons/PencilBoardFillIcon.svelte",
		},
		PencilBoardIcon: {
			path: "lib/icons/PencilBoardIcon.svelte",
		},
		PencilFillIcon: {
			path: "lib/icons/PencilFillIcon.svelte",
		},
		PencilIcon: {
			path: "lib/icons/PencilIcon.svelte",
		},
		PencilLineFillIcon: {
			path: "lib/icons/PencilLineFillIcon.svelte",
		},
		PencilLineIcon: {
			path: "lib/icons/PencilLineIcon.svelte",
		},
		PencilWritingFillIcon: {
			path: "lib/icons/PencilWritingFillIcon.svelte",
		},
		PencilWritingIcon: {
			path: "lib/icons/PencilWritingIcon.svelte",
		},
		PercentIcon: {
			path: "lib/icons/PercentIcon.svelte",
		},
		PersonChatFillIcon: {
			path: "lib/icons/PersonChatFillIcon.svelte",
		},
		PersonChatIcon: {
			path: "lib/icons/PersonChatIcon.svelte",
		},
		PersonCheckmarkFillIcon: {
			path: "lib/icons/PersonCheckmarkFillIcon.svelte",
		},
		PersonCheckmarkIcon: {
			path: "lib/icons/PersonCheckmarkIcon.svelte",
		},
		PersonCircleFillIcon: {
			path: "lib/icons/PersonCircleFillIcon.svelte",
		},
		PersonCircleIcon: {
			path: "lib/icons/PersonCircleIcon.svelte",
		},
		PersonCrossFillIcon: {
			path: "lib/icons/PersonCrossFillIcon.svelte",
		},
		PersonCrossIcon: {
			path: "lib/icons/PersonCrossIcon.svelte",
		},
		PersonEnvelopeFillIcon: {
			path: "lib/icons/PersonEnvelopeFillIcon.svelte",
		},
		PersonEnvelopeIcon: {
			path: "lib/icons/PersonEnvelopeIcon.svelte",
		},
		PersonFillIcon: {
			path: "lib/icons/PersonFillIcon.svelte",
		},
		PersonGavelFillIcon: {
			path: "lib/icons/PersonGavelFillIcon.svelte",
		},
		PersonGavelIcon: {
			path: "lib/icons/PersonGavelIcon.svelte",
		},
		PersonGroupFillIcon: {
			path: "lib/icons/PersonGroupFillIcon.svelte",
		},
		PersonGroupIcon: {
			path: "lib/icons/PersonGroupIcon.svelte",
		},
		PersonHeadsetFillIcon: {
			path: "lib/icons/PersonHeadsetFillIcon.svelte",
		},
		PersonHeadsetIcon: {
			path: "lib/icons/PersonHeadsetIcon.svelte",
		},
		PersonIcon: {
			path: "lib/icons/PersonIcon.svelte",
		},
		PersonMinusFillIcon: {
			path: "lib/icons/PersonMinusFillIcon.svelte",
		},
		PersonMinusIcon: {
			path: "lib/icons/PersonMinusIcon.svelte",
		},
		PersonPencilFillIcon: {
			path: "lib/icons/PersonPencilFillIcon.svelte",
		},
		PersonPencilIcon: {
			path: "lib/icons/PersonPencilIcon.svelte",
		},
		PersonPlusFillIcon: {
			path: "lib/icons/PersonPlusFillIcon.svelte",
		},
		PersonPlusIcon: {
			path: "lib/icons/PersonPlusIcon.svelte",
		},
		PersonPregnantFillIcon: {
			path: "lib/icons/PersonPregnantFillIcon.svelte",
		},
		PersonPregnantIcon: {
			path: "lib/icons/PersonPregnantIcon.svelte",
		},
		PersonRectangleFillIcon: {
			path: "lib/icons/PersonRectangleFillIcon.svelte",
		},
		PersonRectangleIcon: {
			path: "lib/icons/PersonRectangleIcon.svelte",
		},
		PersonSuitFillIcon: {
			path: "lib/icons/PersonSuitFillIcon.svelte",
		},
		PersonSuitIcon: {
			path: "lib/icons/PersonSuitIcon.svelte",
		},
		PersonTallShortFillIcon: {
			path: "lib/icons/PersonTallShortFillIcon.svelte",
		},
		PersonTallShortIcon: {
			path: "lib/icons/PersonTallShortIcon.svelte",
		},
		PhoneFillIcon: {
			path: "lib/icons/PhoneFillIcon.svelte",
		},
		PhoneIcon: {
			path: "lib/icons/PhoneIcon.svelte",
		},
		PieChartFillIcon: {
			path: "lib/icons/PieChartFillIcon.svelte",
		},
		PieChartIcon: {
			path: "lib/icons/PieChartIcon.svelte",
		},
		PiggybankFillIcon: {
			path: "lib/icons/PiggybankFillIcon.svelte",
		},
		PiggybankIcon: {
			path: "lib/icons/PiggybankIcon.svelte",
		},
		PillCircleFillIcon: {
			path: "lib/icons/PillCircleFillIcon.svelte",
		},
		PillCircleIcon: {
			path: "lib/icons/PillCircleIcon.svelte",
		},
		PillCircleRectangleFillIcon: {
			path: "lib/icons/PillCircleRectangleFillIcon.svelte",
		},
		PillCircleRectangleIcon: {
			path: "lib/icons/PillCircleRectangleIcon.svelte",
		},
		PillRectangleFillIcon: {
			path: "lib/icons/PillRectangleFillIcon.svelte",
		},
		PillRectangleIcon: {
			path: "lib/icons/PillRectangleIcon.svelte",
		},
		PinFillIcon: {
			path: "lib/icons/PinFillIcon.svelte",
		},
		PinIcon: {
			path: "lib/icons/PinIcon.svelte",
		},
		PlantFillIcon: {
			path: "lib/icons/PlantFillIcon.svelte",
		},
		PlantIcon: {
			path: "lib/icons/PlantIcon.svelte",
		},
		PlateFillIcon: {
			path: "lib/icons/PlateFillIcon.svelte",
		},
		PlateIcon: {
			path: "lib/icons/PlateIcon.svelte",
		},
		PlayFillIcon: {
			path: "lib/icons/PlayFillIcon.svelte",
		},
		PlayIcon: {
			path: "lib/icons/PlayIcon.svelte",
		},
		PlusCircleFillIcon: {
			path: "lib/icons/PlusCircleFillIcon.svelte",
		},
		PlusCircleIcon: {
			path: "lib/icons/PlusCircleIcon.svelte",
		},
		PlusIcon: {
			path: "lib/icons/PlusIcon.svelte",
		},
		PlusMinusSlashIcon: {
			path: "lib/icons/PlusMinusSlashIcon.svelte",
		},
		PortalFillIcon: {
			path: "lib/icons/PortalFillIcon.svelte",
		},
		PortalIcon: {
			path: "lib/icons/PortalIcon.svelte",
		},
		PresentationFillIcon: {
			path: "lib/icons/PresentationFillIcon.svelte",
		},
		PresentationIcon: {
			path: "lib/icons/PresentationIcon.svelte",
		},
		PrinterLargeFillIcon: {
			path: "lib/icons/PrinterLargeFillIcon.svelte",
		},
		PrinterLargeIcon: {
			path: "lib/icons/PrinterLargeIcon.svelte",
		},
		PrinterLargeTriangleFillIcon: {
			path: "lib/icons/PrinterLargeTriangleFillIcon.svelte",
		},
		PrinterLargeTriangleIcon: {
			path: "lib/icons/PrinterLargeTriangleIcon.svelte",
		},
		PrinterSmallFillIcon: {
			path: "lib/icons/PrinterSmallFillIcon.svelte",
		},
		PrinterSmallIcon: {
			path: "lib/icons/PrinterSmallIcon.svelte",
		},
		PrinterSmallTriangleFillIcon: {
			path: "lib/icons/PrinterSmallTriangleFillIcon.svelte",
		},
		PrinterSmallTriangleIcon: {
			path: "lib/icons/PrinterSmallTriangleIcon.svelte",
		},
		PuzzlePieceFillIcon: {
			path: "lib/icons/PuzzlePieceFillIcon.svelte",
		},
		PuzzlePieceIcon: {
			path: "lib/icons/PuzzlePieceIcon.svelte",
		},
		QrCodeFillIcon: {
			path: "lib/icons/QrCodeFillIcon.svelte",
		},
		QrCodeIcon: {
			path: "lib/icons/QrCodeIcon.svelte",
		},
		QrCodeScanningFillIcon: {
			path: "lib/icons/QrCodeScanningFillIcon.svelte",
		},
		QrCodeScanningIcon: {
			path: "lib/icons/QrCodeScanningIcon.svelte",
		},
		QuestionmarkDiamondFillIcon: {
			path: "lib/icons/QuestionmarkDiamondFillIcon.svelte",
		},
		QuestionmarkDiamondIcon: {
			path: "lib/icons/QuestionmarkDiamondIcon.svelte",
		},
		QuestionmarkIcon: {
			path: "lib/icons/QuestionmarkIcon.svelte",
		},
		QuietZoneFillIcon: {
			path: "lib/icons/QuietZoneFillIcon.svelte",
		},
		QuietZoneIcon: {
			path: "lib/icons/QuietZoneIcon.svelte",
		},
		RaindropFillIcon: {
			path: "lib/icons/RaindropFillIcon.svelte",
		},
		RaindropIcon: {
			path: "lib/icons/RaindropIcon.svelte",
		},
		ReceiptFillIcon: {
			path: "lib/icons/ReceiptFillIcon.svelte",
		},
		ReceiptIcon: {
			path: "lib/icons/ReceiptIcon.svelte",
		},
		ReceptionFillIcon: {
			path: "lib/icons/ReceptionFillIcon.svelte",
		},
		ReceptionIcon: {
			path: "lib/icons/ReceptionIcon.svelte",
		},
		RecordFillIcon: {
			path: "lib/icons/RecordFillIcon.svelte",
		},
		RecordIcon: {
			path: "lib/icons/RecordIcon.svelte",
		},
		RectangleSectionsFillIcon: {
			path: "lib/icons/RectangleSectionsFillIcon.svelte",
		},
		RectangleSectionsIcon: {
			path: "lib/icons/RectangleSectionsIcon.svelte",
		},
		RecycleFillIcon: {
			path: "lib/icons/RecycleFillIcon.svelte",
		},
		RecycleIcon: {
			path: "lib/icons/RecycleIcon.svelte",
		},
		RefrigeratorFillIcon: {
			path: "lib/icons/RefrigeratorFillIcon.svelte",
		},
		RefrigeratorIcon: {
			path: "lib/icons/RefrigeratorIcon.svelte",
		},
		RoadblockFillIcon: {
			path: "lib/icons/RoadblockFillIcon.svelte",
		},
		RoadblockIcon: {
			path: "lib/icons/RoadblockIcon.svelte",
		},
		RobotFillIcon: {
			path: "lib/icons/RobotFillIcon.svelte",
		},
		RobotFrownFillIcon: {
			path: "lib/icons/RobotFrownFillIcon.svelte",
		},
		RobotFrownIcon: {
			path: "lib/icons/RobotFrownIcon.svelte",
		},
		RobotIcon: {
			path: "lib/icons/RobotIcon.svelte",
		},
		RobotSmileFillIcon: {
			path: "lib/icons/RobotSmileFillIcon.svelte",
		},
		RobotSmileIcon: {
			path: "lib/icons/RobotSmileIcon.svelte",
		},
		RocketFillIcon: {
			path: "lib/icons/RocketFillIcon.svelte",
		},
		RocketIcon: {
			path: "lib/icons/RocketIcon.svelte",
		},
		RockingHorseFillIcon: {
			path: "lib/icons/RockingHorseFillIcon.svelte",
		},
		RockingHorseIcon: {
			path: "lib/icons/RockingHorseIcon.svelte",
		},
		RotateLeftFillIcon: {
			path: "lib/icons/RotateLeftFillIcon.svelte",
		},
		RotateLeftIcon: {
			path: "lib/icons/RotateLeftIcon.svelte",
		},
		RotateRightFillIcon: {
			path: "lib/icons/RotateRightFillIcon.svelte",
		},
		RotateRightIcon: {
			path: "lib/icons/RotateRightIcon.svelte",
		},
		RouterIcon: {
			path: "lib/icons/RouterIcon.svelte",
		},
		RulerFillIcon: {
			path: "lib/icons/RulerFillIcon.svelte",
		},
		RulerIcon: {
			path: "lib/icons/RulerIcon.svelte",
		},
		RulersFillIcon: {
			path: "lib/icons/RulersFillIcon.svelte",
		},
		RulersIcon: {
			path: "lib/icons/RulersIcon.svelte",
		},
		SackFillIcon: {
			path: "lib/icons/SackFillIcon.svelte",
		},
		SackIcon: {
			path: "lib/icons/SackIcon.svelte",
		},
		SackKronerFillIcon: {
			path: "lib/icons/SackKronerFillIcon.svelte",
		},
		SackKronerIcon: {
			path: "lib/icons/SackKronerIcon.svelte",
		},
		SackPensionFillIcon: {
			path: "lib/icons/SackPensionFillIcon.svelte",
		},
		SackPensionIcon: {
			path: "lib/icons/SackPensionIcon.svelte",
		},
		SandboxFillIcon: {
			path: "lib/icons/SandboxFillIcon.svelte",
		},
		SandboxIcon: {
			path: "lib/icons/SandboxIcon.svelte",
		},
		ScissorsFillIcon: {
			path: "lib/icons/ScissorsFillIcon.svelte",
		},
		ScissorsIcon: {
			path: "lib/icons/ScissorsIcon.svelte",
		},
		SealCheckmarkFillIcon: {
			path: "lib/icons/SealCheckmarkFillIcon.svelte",
		},
		SealCheckmarkIcon: {
			path: "lib/icons/SealCheckmarkIcon.svelte",
		},
		SealFillIcon: {
			path: "lib/icons/SealFillIcon.svelte",
		},
		SealIcon: {
			path: "lib/icons/SealIcon.svelte",
		},
		SealXMarkFillIcon: {
			path: "lib/icons/SealXMarkFillIcon.svelte",
		},
		SealXMarkIcon: {
			path: "lib/icons/SealXMarkIcon.svelte",
		},
		SectorChartFillIcon: {
			path: "lib/icons/SectorChartFillIcon.svelte",
		},
		SectorChartIcon: {
			path: "lib/icons/SectorChartIcon.svelte",
		},
		ShieldFillIcon: {
			path: "lib/icons/ShieldFillIcon.svelte",
		},
		ShieldIcon: {
			path: "lib/icons/ShieldIcon.svelte",
		},
		ShieldLockFillIcon: {
			path: "lib/icons/ShieldLockFillIcon.svelte",
		},
		ShieldLockIcon: {
			path: "lib/icons/ShieldLockIcon.svelte",
		},
		ShoppingBasketFillIcon: {
			path: "lib/icons/ShoppingBasketFillIcon.svelte",
		},
		ShoppingBasketIcon: {
			path: "lib/icons/ShoppingBasketIcon.svelte",
		},
		ShowerFillIcon: {
			path: "lib/icons/ShowerFillIcon.svelte",
		},
		ShowerIcon: {
			path: "lib/icons/ShowerIcon.svelte",
		},
		ShrinkIcon: {
			path: "lib/icons/ShrinkIcon.svelte",
		},
		SidebarBothFillIcon: {
			path: "lib/icons/SidebarBothFillIcon.svelte",
		},
		SidebarBothIcon: {
			path: "lib/icons/SidebarBothIcon.svelte",
		},
		SidebarLeftFillIcon: {
			path: "lib/icons/SidebarLeftFillIcon.svelte",
		},
		SidebarLeftIcon: {
			path: "lib/icons/SidebarLeftIcon.svelte",
		},
		SidebarRightFillIcon: {
			path: "lib/icons/SidebarRightFillIcon.svelte",
		},
		SidebarRightIcon: {
			path: "lib/icons/SidebarRightIcon.svelte",
		},
		SignLanguageSingleHandFillIcon: {
			path: "lib/icons/SignLanguageSingleHandFillIcon.svelte",
		},
		SignLanguageSingleHandIcon: {
			path: "lib/icons/SignLanguageSingleHandIcon.svelte",
		},
		SignLanguageTwoHandsFillIcon: {
			path: "lib/icons/SignLanguageTwoHandsFillIcon.svelte",
		},
		SignLanguageTwoHandsIcon: {
			path: "lib/icons/SignLanguageTwoHandsIcon.svelte",
		},
		SilhouetteFillIcon: {
			path: "lib/icons/SilhouetteFillIcon.svelte",
		},
		SilhouetteIcon: {
			path: "lib/icons/SilhouetteIcon.svelte",
		},
		SkipBackwardFillIcon: {
			path: "lib/icons/SkipBackwardFillIcon.svelte",
		},
		SkipBackwardIcon: {
			path: "lib/icons/SkipBackwardIcon.svelte",
		},
		SkipForwardFillIcon: {
			path: "lib/icons/SkipForwardFillIcon.svelte",
		},
		SkipForwardIcon: {
			path: "lib/icons/SkipForwardIcon.svelte",
		},
		SnowIcon: {
			path: "lib/icons/SnowIcon.svelte",
		},
		SparkLargeIcon: {
			path: "lib/icons/SparkLargeIcon.svelte",
		},
		SparkSmallIcon: {
			path: "lib/icons/SparkSmallIcon.svelte",
		},
		SparklesFillIcon: {
			path: "lib/icons/SparklesFillIcon.svelte",
		},
		SparklesIcon: {
			path: "lib/icons/SparklesIcon.svelte",
		},
		SpeakerFillIcon: {
			path: "lib/icons/SpeakerFillIcon.svelte",
		},
		SpeakerIcon: {
			path: "lib/icons/SpeakerIcon.svelte",
		},
		SpeakerSlashFillIcon: {
			path: "lib/icons/SpeakerSlashFillIcon.svelte",
		},
		SpeakerSlashIcon: {
			path: "lib/icons/SpeakerSlashIcon.svelte",
		},
		SpeakerSoundWave1FillIcon: {
			path: "lib/icons/SpeakerSoundWave1FillIcon.svelte",
		},
		SpeakerSoundWave1Icon: {
			path: "lib/icons/SpeakerSoundWave1Icon.svelte",
		},
		SpeakerSoundWave2FillIcon: {
			path: "lib/icons/SpeakerSoundWave2FillIcon.svelte",
		},
		SpeakerSoundWave2Icon: {
			path: "lib/icons/SpeakerSoundWave2Icon.svelte",
		},
		SpeakerSoundWave3FillIcon: {
			path: "lib/icons/SpeakerSoundWave3FillIcon.svelte",
		},
		SpeakerSoundWave3Icon: {
			path: "lib/icons/SpeakerSoundWave3Icon.svelte",
		},
		SpoonFillIcon: {
			path: "lib/icons/SpoonFillIcon.svelte",
		},
		SpoonIcon: {
			path: "lib/icons/SpoonIcon.svelte",
		},
		SquarerootIcon: {
			path: "lib/icons/SquarerootIcon.svelte",
		},
		StaircaseIcon: {
			path: "lib/icons/StaircaseIcon.svelte",
		},
		StarFillIcon: {
			path: "lib/icons/StarFillIcon.svelte",
		},
		StarIcon: {
			path: "lib/icons/StarIcon.svelte",
		},
		StarOfLifeFillIcon: {
			path: "lib/icons/StarOfLifeFillIcon.svelte",
		},
		StarOfLifeIcon: {
			path: "lib/icons/StarOfLifeIcon.svelte",
		},
		StarsEuIcon: {
			path: "lib/icons/StarsEuIcon.svelte",
		},
		StethoscopeIcon: {
			path: "lib/icons/StethoscopeIcon.svelte",
		},
		StopFillIcon: {
			path: "lib/icons/StopFillIcon.svelte",
		},
		StopIcon: {
			path: "lib/icons/StopIcon.svelte",
		},
		StrollerFillIcon: {
			path: "lib/icons/StrollerFillIcon.svelte",
		},
		StrollerIcon: {
			path: "lib/icons/StrollerIcon.svelte",
		},
		SunFillIcon: {
			path: "lib/icons/SunFillIcon.svelte",
		},
		SunIcon: {
			path: "lib/icons/SunIcon.svelte",
		},
		TableFillIcon: {
			path: "lib/icons/TableFillIcon.svelte",
		},
		TableIcon: {
			path: "lib/icons/TableIcon.svelte",
		},
		TabletFillIcon: {
			path: "lib/icons/TabletFillIcon.svelte",
		},
		TabletIcon: {
			path: "lib/icons/TabletIcon.svelte",
		},
		TabsAddFillIcon: {
			path: "lib/icons/TabsAddFillIcon.svelte",
		},
		TabsAddIcon: {
			path: "lib/icons/TabsAddIcon.svelte",
		},
		TabsFillIcon: {
			path: "lib/icons/TabsFillIcon.svelte",
		},
		TabsIcon: {
			path: "lib/icons/TabsIcon.svelte",
		},
		TabsRemoveFillIcon: {
			path: "lib/icons/TabsRemoveFillIcon.svelte",
		},
		TabsRemoveIcon: {
			path: "lib/icons/TabsRemoveIcon.svelte",
		},
		TagFillIcon: {
			path: "lib/icons/TagFillIcon.svelte",
		},
		TagIcon: {
			path: "lib/icons/TagIcon.svelte",
		},
		TapWaterFillIcon: {
			path: "lib/icons/TapWaterFillIcon.svelte",
		},
		TapWaterIcon: {
			path: "lib/icons/TapWaterIcon.svelte",
		},
		TasklistFillIcon: {
			path: "lib/icons/TasklistFillIcon.svelte",
		},
		TasklistIcon: {
			path: "lib/icons/TasklistIcon.svelte",
		},
		TasklistSaveFillIcon: {
			path: "lib/icons/TasklistSaveFillIcon.svelte",
		},
		TasklistSaveIcon: {
			path: "lib/icons/TasklistSaveIcon.svelte",
		},
		TasklistSendFillIcon: {
			path: "lib/icons/TasklistSendFillIcon.svelte",
		},
		TasklistSendIcon: {
			path: "lib/icons/TasklistSendIcon.svelte",
		},
		TasklistStartFillIcon: {
			path: "lib/icons/TasklistStartFillIcon.svelte",
		},
		TasklistStartIcon: {
			path: "lib/icons/TasklistStartIcon.svelte",
		},
		TeddyBearFillIcon: {
			path: "lib/icons/TeddyBearFillIcon.svelte",
		},
		TeddyBearIcon: {
			path: "lib/icons/TeddyBearIcon.svelte",
		},
		TenancyFillIcon: {
			path: "lib/icons/TenancyFillIcon.svelte",
		},
		TenancyIcon: {
			path: "lib/icons/TenancyIcon.svelte",
		},
		TerminalFillIcon: {
			path: "lib/icons/TerminalFillIcon.svelte",
		},
		TerminalIcon: {
			path: "lib/icons/TerminalIcon.svelte",
		},
		TestFlaskFillIcon: {
			path: "lib/icons/TestFlaskFillIcon.svelte",
		},
		TestFlaskIcon: {
			path: "lib/icons/TestFlaskIcon.svelte",
		},
		ThermometerFillIcon: {
			path: "lib/icons/ThermometerFillIcon.svelte",
		},
		ThermometerIcon: {
			path: "lib/icons/ThermometerIcon.svelte",
		},
		ThumbDownFillIcon: {
			path: "lib/icons/ThumbDownFillIcon.svelte",
		},
		ThumbDownIcon: {
			path: "lib/icons/ThumbDownIcon.svelte",
		},
		ThumbUpFillIcon: {
			path: "lib/icons/ThumbUpFillIcon.svelte",
		},
		ThumbUpIcon: {
			path: "lib/icons/ThumbUpIcon.svelte",
		},
		TimerFillIcon: {
			path: "lib/icons/TimerFillIcon.svelte",
		},
		TimerIcon: {
			path: "lib/icons/TimerIcon.svelte",
		},
		TimerPauseFillIcon: {
			path: "lib/icons/TimerPauseFillIcon.svelte",
		},
		TimerPauseIcon: {
			path: "lib/icons/TimerPauseIcon.svelte",
		},
		TimerStartFillIcon: {
			path: "lib/icons/TimerStartFillIcon.svelte",
		},
		TimerStartIcon: {
			path: "lib/icons/TimerStartIcon.svelte",
		},
		ToiletFillIcon: {
			path: "lib/icons/ToiletFillIcon.svelte",
		},
		ToiletIcon: {
			path: "lib/icons/ToiletIcon.svelte",
		},
		TokenFillIcon: {
			path: "lib/icons/TokenFillIcon.svelte",
		},
		TokenIcon: {
			path: "lib/icons/TokenIcon.svelte",
		},
		ToothFillIcon: {
			path: "lib/icons/ToothFillIcon.svelte",
		},
		ToothIcon: {
			path: "lib/icons/ToothIcon.svelte",
		},
		TrainFillIcon: {
			path: "lib/icons/TrainFillIcon.svelte",
		},
		TrainIcon: {
			path: "lib/icons/TrainIcon.svelte",
		},
		TramFillIcon: {
			path: "lib/icons/TramFillIcon.svelte",
		},
		TramIcon: {
			path: "lib/icons/TramIcon.svelte",
		},
		TrashFillIcon: {
			path: "lib/icons/TrashFillIcon.svelte",
		},
		TrashIcon: {
			path: "lib/icons/TrashIcon.svelte",
		},
		TrayFoodFillIcon: {
			path: "lib/icons/TrayFoodFillIcon.svelte",
		},
		TrayFoodIcon: {
			path: "lib/icons/TrayFoodIcon.svelte",
		},
		TrendDownIcon: {
			path: "lib/icons/TrendDownIcon.svelte",
		},
		TrendFlatIcon: {
			path: "lib/icons/TrendFlatIcon.svelte",
		},
		TrendUpIcon: {
			path: "lib/icons/TrendUpIcon.svelte",
		},
		TruckFillIcon: {
			path: "lib/icons/TruckFillIcon.svelte",
		},
		TruckIcon: {
			path: "lib/icons/TruckIcon.svelte",
		},
		UmbrellaFillIcon: {
			path: "lib/icons/UmbrellaFillIcon.svelte",
		},
		UmbrellaIcon: {
			path: "lib/icons/UmbrellaIcon.svelte",
		},
		UploadIcon: {
			path: "lib/icons/UploadIcon.svelte",
		},
		VideoFillIcon: {
			path: "lib/icons/VideoFillIcon.svelte",
		},
		VideoIcon: {
			path: "lib/icons/VideoIcon.svelte",
		},
		VideoSlashFillIcon: {
			path: "lib/icons/VideoSlashFillIcon.svelte",
		},
		VideoSlashIcon: {
			path: "lib/icons/VideoSlashIcon.svelte",
		},
		VideoplayerFillIcon: {
			path: "lib/icons/VideoplayerFillIcon.svelte",
		},
		VideoplayerIcon: {
			path: "lib/icons/VideoplayerIcon.svelte",
		},
		VirusFillIcon: {
			path: "lib/icons/VirusFillIcon.svelte",
		},
		VirusIcon: {
			path: "lib/icons/VirusIcon.svelte",
		},
		VitalsIcon: {
			path: "lib/icons/VitalsIcon.svelte",
		},
		WaitingRoomFillIcon: {
			path: "lib/icons/WaitingRoomFillIcon.svelte",
		},
		WaitingRoomIcon: {
			path: "lib/icons/WaitingRoomIcon.svelte",
		},
		WalletFillIcon: {
			path: "lib/icons/WalletFillIcon.svelte",
		},
		WalletIcon: {
			path: "lib/icons/WalletIcon.svelte",
		},
		WateringCanFillIcon: {
			path: "lib/icons/WateringCanFillIcon.svelte",
		},
		WateringCanIcon: {
			path: "lib/icons/WateringCanIcon.svelte",
		},
		WaveformIcon: {
			path: "lib/icons/WaveformIcon.svelte",
		},
		WavesIcon: {
			path: "lib/icons/WavesIcon.svelte",
		},
		WeightIcon: {
			path: "lib/icons/WeightIcon.svelte",
		},
		WheelchairFillIcon: {
			path: "lib/icons/WheelchairFillIcon.svelte",
		},
		WheelchairIcon: {
			path: "lib/icons/WheelchairIcon.svelte",
		},
		WrenchFillIcon: {
			path: "lib/icons/WrenchFillIcon.svelte",
		},
		WrenchIcon: {
			path: "lib/icons/WrenchIcon.svelte",
		},
		XMarkIcon: {
			path: "lib/icons/XMarkIcon.svelte",
		},
		XMarkOctagonFillIcon: {
			path: "lib/icons/XMarkOctagonFillIcon.svelte",
		},
		XMarkOctagonIcon: {
			path: "lib/icons/XMarkOctagonIcon.svelte",
		},
		ZoomMinusFillIcon: {
			path: "lib/icons/ZoomMinusFillIcon.svelte",
		},
		ZoomMinusIcon: {
			path: "lib/icons/ZoomMinusIcon.svelte",
		},
		ZoomPlusFillIcon: {
			path: "lib/icons/ZoomPlusFillIcon.svelte",
		},
		ZoomPlusIcon: {
			path: "lib/icons/ZoomPlusIcon.svelte",
		},
	},
};
