on:
  push:
    tags:
      - v*

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v2

      - name: Install dependencies
        run: |
          cd packages/ds-svelte-community-preprocess-svelte
          bun install
          bun run build # build ds-svelte-community-preprocess-svelte

      - name: Svelte check and lint
        run: |
          cd packages/ds-svelte-community
          bun install
          bun run check
          bun run test

      - name: Build Storybook
        run: |
          cd packages/ds-svelte-community
          bun run build:storybook

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: packages/ds-svelte-community/storybook-static/

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
