name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    permissions:
      contents: "write"
      id-token: "write"
      pull-requests: "write"

    outputs:
      actual_release: ${{ steps.prerelease.outputs.ACTUAL_RELEASE }}
      published: ${{ steps.changesets.outputs.published }}

    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install asdf
        uses: asdf-vm/actions/setup@v3

      - name: asdf cache
        id: asdf-cache
        uses: actions/cache@v4
        with:
          path: ~/.asdf/
          key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}

      - name: Install CD tools from .tool-versions
        if: steps.asdf-cache.outputs.cache-hit != 'true'
        uses: asdf-vm/actions/install@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2" # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: "${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "gh-ds-svelte-community@nais-io.iam.gserviceaccount.com"
          token_format: "access_token"

      - run: bun install
      - run: bun run gar-login && bun run build:libs

      - name: Create Release Pull Request
        uses: changesets/action@v1
        id: changesets
        with:
          createGithubReleases: true
          publish: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Check if pre-release"
        id: "prerelease"
        # Use jq to check if the @nais/ds-svelte-community package is a pre-release
        run: |
          # export ACTUAL_RELEASE=$(echo "${{ steps.changesets.outputs.publishedPackages }}" | jq '.[] | select(.name == "@nais/ds-svelte-community") | .version | contains("-next.") | not')
          export ACTUAL_RELEASE=true
          export MAIN_TAG=$(echo "${{ steps.changesets.outputs.publishedPackages }}" | jq -r '.[] | select(.name == "@nais/ds-svelte-community") | .version')
          echo "ACTUAL_RELEASE=$ACTUAL_RELEASE" >> $GITHUB_OUTPUT
          echo "MAIN_TAG=$MAIN_TAG" >> $GITHUB_OUTPUT

      - name: "Trigger publish_doc workflow"
        if: ${{ steps.changesets.outputs.published == 'true' && steps.prerelease.outputs.ACTUAL_RELEASE == 'true' }}
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.actions.createWorkflowDispatch({
              workflow_file: '.github/workflows/publish_doc.yaml',
              ref: '@nais/ds-svelte-community@${{ steps.prerelease.outputs.MAIN_TAG }}'
            })
