name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    permissions:
      contents: "write"
      id-token: "write"
      pull-requests: "write"

    outputs:
      actual_release: ${{ steps.prerelease.outputs.ACTUAL_RELEASE }}
      published: ${{ steps.changesets.outputs.published }}

    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install asdf
        uses: asdf-vm/actions/setup@v3

      - name: asdf cache
        id: asdf-cache
        uses: actions/cache@v4
        with:
          path: ~/.asdf/
          key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}

      - name: Install CD tools from .tool-versions
        if: steps.asdf-cache.outputs.cache-hit != 'true'
        uses: asdf-vm/actions/install@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2" # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: "${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "gh-ds-svelte-community@nais-io.iam.gserviceaccount.com"
          token_format: "access_token"

      - run: bun install
      - run: bun run gar-login && bun run build:libs

      - name: Create Release Pull Request
        uses: changesets/action@v1
        id: changesets
        with:
          createGithubReleases: true
          publish: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Check if pre-release"
        id: "prerelease"
        # Use jq to check if the @nais/ds-svelte-community package is a pre-release
        run: |
          # export ACTUAL_RELEASE=$(echo "${{ steps.changesets.outputs.publishedPackages }}" | jq '.[] | select(.name == "@nais/ds-svelte-community") | .version | contains("-next.") | not')
          export ACTUAL_RELEASE=true
          echo "ACTUAL_RELEASE=$ACTUAL_RELEASE" >> $GITHUB_OUTPUT

  # Build docs
  build_doc:
    runs-on: ubuntu-latest
    needs: release
    # Only run if @nais/ds-svelte-community is published and version does not contain "-next."
    # It's done with some suboptimal string matching, but it works for now.
    if: ${{ needs.release.outputs.published == 'true' && needs.release.outputs.actual_release == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Install asdf
        uses: asdf-vm/actions/setup@v3

      - name: asdf cache
        id: asdf-cache
        uses: actions/cache@v4
        with:
          path: ~/.asdf/
          key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}

      - name: Install CD tools from .tool-versions
        if: steps.asdf-cache.outputs.cache-hit != 'true'
        uses: asdf-vm/actions/install@v3

      - name: Install dependencies
        run: |
          bun install --frozen-lockfile
          bun run build:libs

      - name: Build docs
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"
        run: |
          cd packages/ds-svelte-community
          bun run build:docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/ds-svelte-community/build/

    # Deploy job
  deploy:
    needs: build_doc

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or the latest "vX.X.X" version tag for this action
