name: Test, lint and check commit
on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - "**"

permissions:
  contents: read

jobs:
  unit_test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Install
        run: |-
          bun install --frozen-lockfile
          bun run build:libs
          bun run sync

      - name: Test and lint ds-svelte-community
        run: |-
          cd packages/ds-svelte-community
          bun run test
          bun run lint
          bun run check

      - name: Test and lint vite-plugin-svelte-docs
        run: |-
          cd packages/vite-plugin-svelte-docs
          bun run test
          bun run lint
          bun run check
