name: Test, lint and check commit
on:
  push:

jobs:
  unit_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version-file: ".tool-versions"
          cache: "npm"

      - name: Install
        run: |-
          npm ci

      - name: Test
        run: |-
          npm run test:unit

  lint_and_check:
    name: Lint and check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version-file: ".tool-versions"
          cache: "npm"

      - name: Install
        run: |-
          npm ci

      - name: Lint and check
        run: |-
          npm run lint
          npm run check
