name: Test, lint and check commit
on:
  push:
    branches: "*"

jobs:
  unit_test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find bun version
        id: bun_version
        run: |
          echo "BUN_VERSION=$(grep bun .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version-file: ".tool-versions"

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ steps.bun_version.outputs.BUN_VERSION }}

      - name: Install
        run: |-
          bun install --frozen-lockfile
          cd packages/ds-svelte-community-preprocess-svelte
          bun run build # build ds-svelte-community-preprocess-svelte

      - name: Test and lint ds-svelte-community
        run: |-
          cd packages/ds-svelte-community
          bun run build
          bun run test
          bun run lint
          bun run check
      - name: Test and lint ds-svelte-community-preprocess-svelte
        run: |-
          cd packages/ds-svelte-community-preprocess-svelte
          bun run test
          bun run lint
          bun run check
