name: Test, lint and check commit
on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - "**"

permissions:
  contents: read
  pull-requests: write

jobs:
  unit_test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: jdx/mise-action@v3

      - name: Install
        run: |-
          bun install --frozen-lockfile
          bun run build:libs
          bun run sync

      - name: Test and lint ds-svelte-community
        id: test
        continue-on-error: true
        env:
          VISUAL_TESTS: "true"
        run: |-
          cd packages/ds-svelte-community
          bun run test --timeout 30000
          bun run lint
          bun run check

      - name: Report visual test failures
        if: steps.test.outcome == 'failure' && github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |-
          cd packages/ds-svelte-community
          bun run scripts/visual-test-reporter.ts

      - name: Fail if tests failed
        if: steps.test.outcome == 'failure'
        run: exit 1

      - name: Test and lint vite-plugin-svelte-docs
        run: |-
          cd packages/vite-plugin-svelte-docs
          bun run test
          bun run lint
          bun run check
