name: Test, lint and check commit
on:
  push:
    branches: "*"

jobs:
  unit_test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v2

      - name: Install
        run: |-
          cd packages/ds-svelte-community-preprocess-svelte
          bun install
          bun run build # build ds-svelte-community-preprocess-svelte

      - name: Test and lint ds-svelte-community
        run: |-
          cd packages/ds-svelte-community
          bun install
          bun run build
          bun run test
          bun run lint
          bun run check

      - name: Test and lint ds-svelte-community-preprocess-svelte
        run: |-
          cd packages/ds-svelte-community-preprocess-svelte
          bun install
          bun run test
          bun run lint
          bun run check
